config/routes.rb
Rtestserver::Application.routes.draw do
  resources :testbed_owners

  resources :test_cases

  resources :testbeds

  get "home/index"

end

app/models/test_case.rb
class TestCase < ActiveRecord::Base
  belongs_to :testbed
end

app/models/testbed.rb
class Testbed < ActiveRecord::Base
  has_many  :tests
end

app/models/testbed_owner.rb
class TestbedOwner < ActiveRecord::Base
  has_one :testbed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/test_cases_controller.rb
class TestCasesController < ApplicationController
  # GET /test_cases
  # GET /test_cases.json
  def index
    @test_cases = TestCase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_cases }
    end
  end

  # GET /test_cases/1
  # GET /test_cases/1.json
  def show
    @test_case = TestCase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_case }
    end
  end

  # GET /test_cases/new
  # GET /test_cases/new.json
  def new
    @test_case = TestCase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_case }
    end
  end

  # GET /test_cases/1/edit
  def edit
    @test_case = TestCase.find(params[:id])
  end

  # POST /test_cases
  # POST /test_cases.json
  def create
    @test_case = TestCase.new(params[:test_case])

    respond_to do |format|
      if @test_case.save
        format.html { redirect_to @test_case, notice: 'Test case was successfully created.' }
        format.json { render json: @test_case, status: :created, location: @test_case }
      else
        format.html { render action: "new" }
        format.json { render json: @test_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_cases/1
  # PUT /test_cases/1.json
  def update
    @test_case = TestCase.find(params[:id])

    respond_to do |format|
      if @test_case.update_attributes(params[:test_case])
        format.html { redirect_to @test_case, notice: 'Test case was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_cases/1
  # DELETE /test_cases/1.json
  def destroy
    @test_case = TestCase.find(params[:id])
    @test_case.destroy

    respond_to do |format|
      format.html { redirect_to test_cases_url }
      format.json { head :ok }
    end
  end
end

app/controllers/testbed_owners_controller.rb
class TestbedOwnersController < ApplicationController
  # GET /testbed_owners
  # GET /testbed_owners.json
  def index
    @testbed_owners = TestbedOwner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testbed_owners }
    end
  end

  # GET /testbed_owners/1
  # GET /testbed_owners/1.json
  def show
    @testbed_owner = TestbedOwner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testbed_owner }
    end
  end

  # GET /testbed_owners/new
  # GET /testbed_owners/new.json
  def new
    @testbed_owner = TestbedOwner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testbed_owner }
    end
  end

  # GET /testbed_owners/1/edit
  def edit
    @testbed_owner = TestbedOwner.find(params[:id])
  end

  # POST /testbed_owners
  # POST /testbed_owners.json
  def create
    @testbed_owner = TestbedOwner.new(params[:testbed_owner])

    respond_to do |format|
      if @testbed_owner.save
        format.html { redirect_to @testbed_owner, notice: 'Testbed owner was successfully created.' }
        format.json { render json: @testbed_owner, status: :created, location: @testbed_owner }
      else
        format.html { render action: "new" }
        format.json { render json: @testbed_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testbed_owners/1
  # PUT /testbed_owners/1.json
  def update
    @testbed_owner = TestbedOwner.find(params[:id])

    respond_to do |format|
      if @testbed_owner.update_attributes(params[:testbed_owner])
        format.html { redirect_to @testbed_owner, notice: 'Testbed owner was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @testbed_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testbed_owners/1
  # DELETE /testbed_owners/1.json
  def destroy
    @testbed_owner = TestbedOwner.find(params[:id])
    @testbed_owner.destroy

    respond_to do |format|
      format.html { redirect_to testbed_owners_url }
      format.json { head :ok }
    end
  end
end

app/controllers/testbeds_controller.rb
class TestbedsController < ApplicationController
  # GET /testbeds
  # GET /testbeds.json
  def index
    @testbeds = Testbed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testbeds }
    end
  end

  # GET /testbeds/1
  # GET /testbeds/1.json
  def show
    @testbed = Testbed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testbed }
    end
  end

  # GET /testbeds/new
  # GET /testbeds/new.json
  def new
    @testbed = Testbed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testbed }
    end
  end

  # GET /testbeds/1/edit
  def edit
    @testbed = Testbed.find(params[:id])
  end

  # POST /testbeds
  # POST /testbeds.json
  def create
    @testbed = Testbed.new(params[:testbed])

    respond_to do |format|
      if @testbed.save
        format.html { redirect_to @testbed, notice: 'Testbed was successfully created.' }
        format.json { render json: @testbed, status: :created, location: @testbed }
      else
        format.html { render action: "new" }
        format.json { render json: @testbed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testbeds/1
  # PUT /testbeds/1.json
  def update
    @testbed = Testbed.find(params[:id])

    respond_to do |format|
      if @testbed.update_attributes(params[:testbed])
        format.html { redirect_to @testbed, notice: 'Testbed was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @testbed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testbeds/1
  # DELETE /testbeds/1.json
  def destroy
    @testbed = Testbed.find(params[:id])
    @testbed.destroy

    respond_to do |format|
      format.html { redirect_to testbeds_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/test_cases_helper.rb
module TestCasesHelper
end

app/helpers/testbed_owners_helper.rb
module TestbedOwnersHelper
end

app/helpers/testbeds_helper.rb
module TestbedsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rtestserver</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/test_cases/_form.html.erb
<%= form_for(@test_case) do |f| %>
  <% if @test_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_case.errors.count, "error") %> prohibited this test_case from being saved:</h2>

      <ul>
      <% @test_case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :procedure %><br />
    <%= f.text_area :procedure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_cases/edit.html.erb
<h1>Editing test_case</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_case %> |
<%= link_to 'Back', test_cases_path %>

app/views/test_cases/index.html.erb
<h1>Listing test_cases</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Description</th>
    <th>Procedure</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @test_cases.each do |test_case| %>
  <tr>
    <td><%= test_case.name %></td>
    <td><%= test_case.title %></td>
    <td><%= test_case.description %></td>
    <td><%= test_case.procedure %></td>
    <td><%= link_to 'Show', test_case %></td>
    <td><%= link_to 'Edit', edit_test_case_path(test_case) %></td>
    <td><%= link_to 'Destroy', test_case, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Test case', new_test_case_path %>

app/views/test_cases/new.html.erb
<h1>New test_case</h1>

<%= render 'form' %>

<%= link_to 'Back', test_cases_path %>

app/views/test_cases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @test_case.name %>
</p>

<p>
  <b>Title:</b>
  <%= @test_case.title %>
</p>

<p>
  <b>Description:</b>
  <%= @test_case.description %>
</p>

<p>
  <b>Procedure:</b>
  <%= @test_case.procedure %>
</p>


<%= link_to 'Edit', edit_test_case_path(@test_case) %> |
<%= link_to 'Back', test_cases_path %>

app/views/testbed_owners/_form.html.erb
<%= form_for(@testbed_owner) do |f| %>
  <% if @testbed_owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testbed_owner.errors.count, "error") %> prohibited this testbed_owner from being saved:</h2>

      <ul>
      <% @testbed_owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :coreid %><br />
    <%= f.text_field :coreid %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testbed_owners/edit.html.erb
<h1>Editing testbed_owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @testbed_owner %> |
<%= link_to 'Back', testbed_owners_path %>

app/views/testbed_owners/index.html.erb
<h1>Listing testbed_owners</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Coreid</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @testbed_owners.each do |testbed_owner| %>
  <tr>
    <td><%= testbed_owner.name %></td>
    <td><%= testbed_owner.coreid %></td>
    <td><%= testbed_owner.description %></td>
    <td><%= link_to 'Show', testbed_owner %></td>
    <td><%= link_to 'Edit', edit_testbed_owner_path(testbed_owner) %></td>
    <td><%= link_to 'Destroy', testbed_owner, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Testbed owner', new_testbed_owner_path %>

app/views/testbed_owners/new.html.erb
<h1>New testbed_owner</h1>

<%= render 'form' %>

<%= link_to 'Back', testbed_owners_path %>

app/views/testbed_owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @testbed_owner.name %>
</p>

<p>
  <b>Coreid:</b>
  <%= @testbed_owner.coreid %>
</p>

<p>
  <b>Description:</b>
  <%= @testbed_owner.description %>
</p>


<%= link_to 'Edit', edit_testbed_owner_path(@testbed_owner) %> |
<%= link_to 'Back', testbed_owners_path %>

app/views/testbeds/_form.html.erb
<%= form_for(@testbed) do |f| %>
  <% if @testbed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testbed.errors.count, "error") %> prohibited this testbed from being saved:</h2>

      <ul>
      <% @testbed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testbeds/edit.html.erb
<h1>Editing testbed</h1>

<%= render 'form' %>

<%= link_to 'Show', @testbed %> |
<%= link_to 'Back', testbeds_path %>

app/views/testbeds/index.html.erb
<h1>Listing testbeds</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @testbeds.each do |testbed| %>
  <tr>
    <td><%= testbed.name %></td>
    <td><%= testbed.title %></td>
    <td><%= testbed.description %></td>
    <td><%= link_to 'Show', testbed %></td>
    <td><%= link_to 'Edit', edit_testbed_path(testbed) %></td>
    <td><%= link_to 'Destroy', testbed, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Testbed', new_testbed_path %>

app/views/testbeds/new.html.erb
<h1>New testbed</h1>

<%= render 'form' %>

<%= link_to 'Back', testbeds_path %>

app/views/testbeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @testbed.name %>
</p>

<p>
  <b>Title:</b>
  <%= @testbed.title %>
</p>

<p>
  <b>Description:</b>
  <%= @testbed.description %>
</p>


<%= link_to 'Edit', edit_testbed_path(@testbed) %> |
<%= link_to 'Back', testbeds_path %>